mysqladmin:
  username: "xiaom"
#  password: "Server@1234.com"
#  path: "127.0.0.1:3306"
  password: "123456"
  path: "nas.xiaom.work:3306"
  dbname: "qmPlus"
  config: "charset=utf8&parseTime=True&loc=Local"

redisadmin:
  path: "nas.xiaom.work:6379"

jwt:
  JwtKey: eva0209

sessions:
  SecretKey: ses9090

casbin:
  modelPath: "./resource/rbac_model.conf"